!!---------------------------WRITERESUME---------------------------!!
SUBROUTINE WRITERESUME(ISTEP, DDR, FSSRCH , P)
   USE COMMONMOD
   USE MLPGKINE
   USE MLPGSTORAGE
   IMPLICIT NONE

   INTEGER(KIND=4),INTENT(IN)::ISTEP
   REAL(KIND=8),INTENT(IN)::DDR(NODEID(0)), P(LNODE)
   LOGICAL,INTENT(IN)::FSSRCH(NODEID(0))

   INTEGER(KIND=4)::I, MF
   CHARACTER(LEN=256)::RESF

   WRITE(RESF,'(I9.9)')ISTEP
   RESF = "Output/Resume_"//TRIM(RESF)//".txt"
   WRITE(*,*)TRIM(RESF)

   OPEN(NEWUNIT = MF, FILE=TRIM(RESF), FORM = 'UNFORMATTED')

   WRITE(MF) ISTEP
   WRITE(MF) TOTAL_TIME

   WRITE(MF) NODEID(-7:LNODE)

   WRITE(MF) NWALLID(:,1)
   WRITE(MF) NWALLID(:,2)
   WRITE(MF) NWALLID(:,3)
   WRITE(MF) NWALLID(:,4)

   WRITE(MF)  COORX(:,1)
   WRITE(MF)  COORX(:,2)
   WRITE(MF)  COORX(:,3)

   WRITE(MF)  COORY(:,1)
   WRITE(MF)  COORY(:,2)
   WRITE(MF)  COORY(:,3)

   WRITE(MF)  COORZ(:,1)
   WRITE(MF)  COORZ(:,2)
   WRITE(MF)  COORZ(:,3)

   WRITE(MF)  SNX(:)
   WRITE(MF)  SNY(:)
   WRITE(MF)  SNZ(:)

   WRITE(MF)  SMX(:)
   WRITE(MF)  SMY(:)
   WRITE(MF)  SMZ(:)

   WRITE(MF)  SSX(:)
   WRITE(MF)  SSY(:)
   WRITE(MF)  SSZ(:)

   WRITE(MF)  DDR(:)

   WRITE(MF)  UX(:,1)
   WRITE(MF)  UX(:,2)
   WRITE(MF)  UX(:,3)
   WRITE(MF)  UX(:,4)

   WRITE(MF)  UY(:,1)
   WRITE(MF)  UY(:,2)
   WRITE(MF)  UY(:,3)
   WRITE(MF)  UY(:,4)

   WRITE(MF)  UZ(:,1)
   WRITE(MF)  UZ(:,2)
   WRITE(MF)  UZ(:,3)
   WRITE(MF)  UZ(:,4)

   WRITE(MF)  FSSRCH(:)

   WRITE(MF)  P(:)
   WRITE(MF)  PTCSR(1:NODEID(-1))

   CLOSE(MF)

END SUBROUTINE WRITERESUME
!!-------------------------END WRITERESUME-------------------------!!

!!---------------------------READRESUME----------------------------!!
SUBROUTINE READRESUME(RESUMEFILE, ISTEP, DDR, FSSRCH , P)
   USE COMMONMOD
   USE MLPGKINE
   USE MLPGSTORAGE
   IMPLICIT NONE

   INTEGER(KIND=4),INTENT(OUT)::ISTEP
   REAL(KIND=8),INTENT(OUT)::DDR(NODEID(0)), P(LNODE)
   LOGICAL,INTENT(OUT)::FSSRCH(NODEID(0))
   CHARACTER(LEN=256),INTENT(IN)::RESUMEFILE

   INTEGER(KIND=4)::I, MF
   LOGICAL::EX

   INQUIRE(FILE=TRIM(RESUMEFILE), EXIST = EX)
   IF(EX)THEN
      OPEN(NEWUNIT = MF, FILE=TRIM(RESUMEFILE), FORM = 'UNFORMATTED')
   ELSE
      WRITE(*,*)"[ERR] RESUME FILE MISSING"
   ENDIF

   READ(MF) ISTEP
   READ(MF) TOTAL_TIME

   READ(MF) NODEID(-7:LNODE)

   READ(MF) NWALLID(1:LNODE,1)
   READ(MF) NWALLID(1:LNODE,2)
   READ(MF) NWALLID(1:LNODE,3)
   READ(MF) NWALLID(1:LNODE,4)

   READ(MF)  COORX(1:LNODE,1)
   READ(MF)  COORX(1:LNODE,2)
   READ(MF)  COORX(1:LNODE,3)

   READ(MF)  COORY(1:LNODE,1)
   READ(MF)  COORY(1:LNODE,2)
   READ(MF)  COORY(1:LNODE,3)

   READ(MF)  COORZ(1:LNODE,1)
   READ(MF)  COORZ(1:LNODE,2)
   READ(MF)  COORZ(1:LNODE,3)

   READ(MF)  SNX(1:LNODE)
   READ(MF)  SNY(1:LNODE)
   READ(MF)  SNZ(1:LNODE)

   READ(MF)  SMX(1:LNODE)
   READ(MF)  SMY(1:LNODE)
   READ(MF)  SMZ(1:LNODE)

   READ(MF)  SSX(1:LNODE)
   READ(MF)  SSY(1:LNODE)
   READ(MF)  SSZ(1:LNODE)

   READ(MF)  DDR(1:NODEID(0))

   READ(MF)  UX(1:NODEID(0),1)
   READ(MF)  UX(1:NODEID(0),2)
   READ(MF)  UX(1:NODEID(0),3)
   READ(MF)  UX(1:NODEID(0),4)

   READ(MF)  UY(1:NODEID(0),1)
   READ(MF)  UY(1:NODEID(0),2)
   READ(MF)  UY(1:NODEID(0),3)
   READ(MF)  UY(1:NODEID(0),4)

   READ(MF)  UZ(1:NODEID(0),1)
   READ(MF)  UZ(1:NODEID(0),2)
   READ(MF)  UZ(1:NODEID(0),3)
   READ(MF)  UZ(1:NODEID(0),4)

   READ(MF)  FSSRCH(1:NODEID(0))

   READ(MF)  P(1:LNODE)
   READ(MF)  PTCSR(1:NODEID(-1))
   CLOSE(MF)
END SUBROUTINE READRESUME
!!-------------------------END READRESUME--------------------------!!
